#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install nginx -y

sudo echo "hello World!" > /var/www/html/index.nginx-debian.html

new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

service nginx start
