#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" > /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

echo "global
   log 127.0.0.1 local0 notice
   maxconn 2000
   user haproxy
   group haproxy
defaults
   log   global
   mode  http
   option  httplog
   option  dontlognull
   retries 3
   option redispatch
   timeout connect  5000
   timeout client  10000
   timeout server  10000
frontend www-https
    bind   0.0.0.0:80
    option forwardfor
    default_backend www-backend
backend www-backend
    balance  roundrobin
    server 158828-web-01 100.26.49.247 check
    server 158828-web-02 54.173.27.192 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
