#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg
sudo chown $USER:$USER /etc/default/haproxy

server_config=\
"
frontend main
	bind *:80
	mode http
	default_backend web-server

backend web-server
    balance  roundrobin
    mode http
    server 158828-web-01 100.26.49.247 check
    server 158828-web-02 54.173.27.192 check
"

sudo echo "$server_config" >> /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
