#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

CONF="\
frontend main
	bind *:80
	mode http
	default_backend web-server

backend web-server
    balance  roundrobin
    server 158828-web-01 100.26.49.247 check
    server 158828-web-02 54.173.27.192 check
"
echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
